logging:
  file:
    name: C:/springcloudtraining/temp/spring-boot-elk.log

server:
  port: 9093

spring:
  application:
    name: ServiceOne
  zipkin:
    base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)


